### PR TITLE
Russian language strings did not fit the buttons. Fixed.

### PR DESCRIPTION
**Pull request by crea7or**
Fixed two values FeedbackYes and RatingYes because they didn't fit the button. Don't know why VS changed the order of the elements in the some other xml tags.

### CODE REVIEW

**Comment by ltomuta** [comment]
Can you please fix these strings in the GetLocalization project instead? Otherwise we risk rolling back your fix when we next pull the localizations from there...

Best regards,
Lucian

Sent from my Nokia Lumia 920 powered by Windows Phone 8

**Comment by crea7or** [comment]
no problem, but how to find RateMyApp there?

**Comment by ltomuta** [comment]
There is a link in project's readme, just scroll down on project's home page.

Should be http://www.getlocalization.com/ratemyapp

Lucian

Sent from my Nokia Lumia 920 powered by Windows Phone 8

**Comment by crea7or** [comment]
Done!

**Comment by ltomuta** [comment]
Great, we'll have the fix in the next release. Meanwhile I will close this pull request.

**Pull request closed without merging**
