### PR TITLE
Fix for not counting launches if using Application.Current.Terminate() (+few private to public changes)

### PR DESCRIPTION
**Pull request by deluksic**
Make FeedbackOverlay.Feedback() public. It is a very useful method. 
Also, make FeedbackHelper.Store/LoadState() public and save IsolatedStorageSettings manually instead of waiting for the app to do it, because sometimes developers use Application.Current.Terminate() and in that case the app doesn't remember the launch count correctly after shutting down.

### CODE REVIEW

**Comment by deluksic** [comment]
Oh, sorry I didn't see that I changed the versioning by opening and saving in VS2013.. Please exclude those changes if you can..

**Comment by deluksic** [comment]
This pull request fixes this Issue: https://github.com/nokia-developer/rate-my-app/issues/36

**Comment by ltomuta** [comment]
Hi @deluksic,

I will have a look at this. My plan was to open Feedback in the helper class since when calling it from outside the RMA component there's no need to have the RMA control at all. As for saving the data, it should be enough to call "save" on the settings as data changes, no explicit call before exit (and therefore no public save method).

Best regards,
Lucian

**Comment by deluksic** [comment]
Yes, makes sense.

**Pull request closed without merging**
